TYPE=VIEW
query=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,`ad`.`agama` AS `agama`,`ad`.`foto` AS `foto`,`ad`.`id_provinsi` AS `id_provinsi`,`ad`.`id_kota` AS `id_kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,`ao`.`id_provinsi` AS `id_provinsi_ot`,`ao`.`id_kota` AS `id_kota_ot`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ap`.`username` AS `username` from (((((`db_alumni`.`aluni_anggota_dasar` `ad` join `db_alumni`.`aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `db_alumni`.`aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `db_alumni`.`aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`))) join `db_alumni`.`aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `db_alumni`.`aluni_pengguna` `ap` on((`ad`.`id_anggota` = `ap`.`id_anggota`)))
md5=2bf50b1c07d6093f8d1dbbaaf0632af2
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-05-27 05:50:55
create-version=2
source=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,`ad`.`agama` AS `agama`,`ad`.`foto` AS `foto`,`ad`.`id_provinsi` AS `id_provinsi`,`ad`.`id_kota` AS `id_kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,`ao`.`id_provinsi` AS `id_provinsi_ot`,`ao`.`id_kota` AS `id_kota_ot`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ap`.`username` AS `username` from (((((`aluni_anggota_dasar` `ad` join `aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`))) join `aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `aluni_pengguna` `ap` on((`ad`.`id_anggota` = `ap`.`id_anggota`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,`ad`.`agama` AS `agama`,`ad`.`foto` AS `foto`,`ad`.`id_provinsi` AS `id_provinsi`,`ad`.`id_kota` AS `id_kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,`ao`.`id_provinsi` AS `id_provinsi_ot`,`ao`.`id_kota` AS `id_kota_ot`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ap`.`username` AS `username` from (((((`db_alumni`.`aluni_anggota_dasar` `ad` join `db_alumni`.`aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `db_alumni`.`aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `db_alumni`.`aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`))) join `db_alumni`.`aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `db_alumni`.`aluni_pengguna` `ap` on((`ad`.`id_anggota` = `ap`.`id_anggota`)))
mariadb-version=100113
