TYPE=VIEW
query=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,(select `db_alumni`.`aluni_m_agama`.`nama_agama` from `db_alumni`.`aluni_m_agama` where (`db_alumni`.`aluni_m_agama`.`id_agama` = `ad`.`agama`)) AS `agama`,`ad`.`foto` AS `foto`,(select `db_alumni`.`aluni_m_provinsi`.`nama_provinsi` from `db_alumni`.`aluni_m_provinsi` where (`db_alumni`.`aluni_m_provinsi`.`id_provinsi` = `ad`.`id_provinsi`)) AS `provinsi`,(select `db_alumni`.`aluni_m_kota`.`nama_kota` from `db_alumni`.`aluni_m_kota` where (`db_alumni`.`aluni_m_kota`.`id_kota` = `ad`.`id_kota`)) AS `kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,(select `db_alumni`.`aluni_m_provinsi`.`nama_provinsi` from `db_alumni`.`aluni_m_provinsi` where (`db_alumni`.`aluni_m_provinsi`.`id_provinsi` = `ao`.`id_provinsi`)) AS `provinsi_orang_tua`,(select `db_alumni`.`aluni_m_kota`.`nama_kota` from `db_alumni`.`aluni_m_kota` where (`db_alumni`.`aluni_m_kota`.`id_kota` = `ao`.`id_kota`)) AS `kota_orang_tua`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter` from ((((`db_alumni`.`aluni_anggota_dasar` `ad` join `db_alumni`.`aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `db_alumni`.`aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `db_alumni`.`aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `db_alumni`.`aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`)))
md5=22e1c2db25bc6551cedfabb19cffbb53
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-05-27 05:50:55
create-version=2
source=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,(select `aluni_m_agama`.`nama_agama` from `aluni_m_agama` where (`aluni_m_agama`.`id_agama` = `ad`.`agama`)) AS `agama`,`ad`.`foto` AS `foto`,(select `aluni_m_provinsi`.`nama_provinsi` from `aluni_m_provinsi` where (`aluni_m_provinsi`.`id_provinsi` = `ad`.`id_provinsi`)) AS `provinsi`,(select `aluni_m_kota`.`nama_kota` from `aluni_m_kota` where (`aluni_m_kota`.`id_kota` = `ad`.`id_kota`)) AS `kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,(select `aluni_m_provinsi`.`nama_provinsi` from `aluni_m_provinsi` where (`aluni_m_provinsi`.`id_provinsi` = `ao`.`id_provinsi`)) AS `provinsi_orang_tua`,(select `aluni_m_kota`.`nama_kota` from `aluni_m_kota` where (`aluni_m_kota`.`id_kota` = `ao`.`id_kota`)) AS `kota_orang_tua`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter` from ((((`aluni_anggota_dasar` `ad` join `aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `ad`.`id_anggota` AS `id_anggota`,`ad`.`nama_lengkap` AS `nama_lengkap`,`ad`.`nama_panggilan` AS `nama_panggilan`,`ad`.`jenis_kelamin` AS `jenis_kelamin`,`ad`.`tempat_lahir` AS `tempat_lahir`,`ad`.`tanggal_lahir` AS `tanggal_lahir`,(select `db_alumni`.`aluni_m_agama`.`nama_agama` from `db_alumni`.`aluni_m_agama` where (`db_alumni`.`aluni_m_agama`.`id_agama` = `ad`.`agama`)) AS `agama`,`ad`.`foto` AS `foto`,(select `db_alumni`.`aluni_m_provinsi`.`nama_provinsi` from `db_alumni`.`aluni_m_provinsi` where (`db_alumni`.`aluni_m_provinsi`.`id_provinsi` = `ad`.`id_provinsi`)) AS `provinsi`,(select `db_alumni`.`aluni_m_kota`.`nama_kota` from `db_alumni`.`aluni_m_kota` where (`db_alumni`.`aluni_m_kota`.`id_kota` = `ad`.`id_kota`)) AS `kota`,`ad`.`alamat` AS `alamat`,`ad`.`aktif` AS `aktif`,`aa`.`angkatan` AS `angkatan`,`aa`.`tahun_masuk` AS `tahun_masuk`,`aa`.`tahun_keluar` AS `tahun_keluar`,`aa`.`kelas_terakhir` AS `kelas_terakhir`,`aa`.`catatan` AS `catatan`,`ak`.`nama_pasangan` AS `nama_pasangan`,`ak`.`nama_anak` AS `nama_anak`,`ao`.`nama_ayah` AS `nama_ayah`,`ao`.`nama_ibu` AS `nama_ibu`,`ao`.`nama_wali` AS `nama_wali`,(select `db_alumni`.`aluni_m_provinsi`.`nama_provinsi` from `db_alumni`.`aluni_m_provinsi` where (`db_alumni`.`aluni_m_provinsi`.`id_provinsi` = `ao`.`id_provinsi`)) AS `provinsi_orang_tua`,(select `db_alumni`.`aluni_m_kota`.`nama_kota` from `db_alumni`.`aluni_m_kota` where (`db_alumni`.`aluni_m_kota`.`id_kota` = `ao`.`id_kota`)) AS `kota_orang_tua`,`ao`.`alamat_orang_tua` AS `alamat_orang_tua`,`ako`.`no_rumah` AS `no_rumah`,`ako`.`no_handphone` AS `no_handphone`,`ako`.`no_handphone2` AS `no_handphone2`,`ako`.`pin_blackberry` AS `pin_blackberry`,`ako`.`alamat_email` AS `alamat_email`,`ako`.`alamat_website` AS `alamat_website`,`ako`.`facebook` AS `facebook`,`ako`.`twitter` AS `twitter` from ((((`db_alumni`.`aluni_anggota_dasar` `ad` join `db_alumni`.`aluni_anggota_akademik` `aa` on((`ad`.`id_anggota` = `aa`.`id_anggota`))) join `db_alumni`.`aluni_anggota_keluarga` `ak` on((`ad`.`id_anggota` = `ak`.`id_anggota`))) join `db_alumni`.`aluni_anggota_orang_tua` `ao` on((`ad`.`id_anggota` = `ao`.`id_anggota`))) join `db_alumni`.`aluni_anggota_kontak` `ako` on((`ad`.`id_anggota` = `ako`.`id_anggota`)))
mariadb-version=100113
